server:
  port: 8084
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1KB


spring:
  application.name: sample-circuit-break
  profiles.active:
    - dev


  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  jackson:
    time-zone: Brazil/East
    locale: pt_BR

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health.show-details: always

feign:
  client.config:
    default:
      logger-level: FULL
      connect-timeout: 400
  hystrix:
    enabled:

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    environment: ${spring.profiles.active}